## Documentation for Navigating the Item Metadata

This is a user's guide to navigating the item metadata (metadata-ABCD-items.csv). The csv file contains several columns meant to help navigate the ABCD dataset while working in R or similar statistical programming languages.

| Column                                                                           | Origin                       | Contents                                                                                                                                                                                                                                   |
|----------------------------------------------------------------------------------|------------------------------|--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|
| [domain]                                                                         | ABCD metadata                | a sorting system that all ABCD 6.0 release variables were sorted into                                                                                                                                                                      |
| [sub_domain]                                                                     | ABCD metadata                | a subsystem within domain that all ABCD 6.0 release variables were sorted into                                                                                                                                                             |
| [source]                                                                         | ABCD metadata                | allows us to quickly tell who the respondent/subject was                                                                                                                                                                                   |
| [table_name]                                                                     | ABCD metadata                | collections of ABCD variables that were administered and/or collected together                                                                                                                                                             |
| [variable]                                                                       | ABCD metadata and Pelham Lab | name of the item; mostly derived from ABCD 6.0 metadata; some created by the Pelham Lab through manipulation                                                                                                                               |
| [label]                                                                          | ABCD metadata and Pelham Lab | describes the contents of the variable in more detail                                                                                                                                                                                      |
| [has_branching_logic]                                                            | Pelham Lab                   | a yes/no indication of the presence of gating                                                                                                                                                                                              |
| [sensitivity]                                                                    | Pelham Lab                   | an evaluation of how sensitive the content of the variable is                                                                                                                                                                              |
| [plab_facet]                                                                     | Pelham Lab                   | a sorting system that all ABCD 6.0 release variables and Pelham Lab variables were sorted into                                                                                                                                             |
| [plab_subfacet]                                                                  | Pelham Lab                   | a subsystem within domain that all ABCD 6.0 release and Pelham Lab variables were sorted into                                                                                                                                              |
| [alexsa_facet]                                                                   | Pelham Lab                   | utilizes the subscales from the Assessment of Liability and EXposure to Substance use and Antisocial behavior for Children (ALEXSA) assessment ([Ridenour et al., 2009](https://pubmed.ncbi.nlm.nih.gov/20180677/)) to sort variables into |
| [nobs_00mo, nobs_12mo, nobs_24mo, nobs_36mo, nobs_48mo, nobs_60mo, or nobs_72mo] | Pelham Lab                   | counts number of observations (nobs) in any given wave of ABCD data collection for a given item                                                                                                                                            |

### domain

The domain is a sorting system originating from the ABCD metadata that groups all items into the following broad categories:

-   ABCD (General)

-   Friends, Family, & Community

-   Mental Health

-   Neurocognition

-   Novel Technologies

-   Physical Health

-   Substance Use

There are more domains in ABCD -- these are just the ones represented in TSP-ABCD.

### sub_domain

The sub_domain is a sorting system originating from the ABCD metadata that groups items into the following categories within domains:

-   Actigraphy

-   Administrative

-   Broad Psychopathology

-   Cognition

-   Community

-   Culture

-   Demographics

-   Development

-   Emotion

-   Family

-   Medical

-   Mood

-   Nutrition

-   Parenting

-   Peers

-   Physical Health

-   Psychosis

-   Psychosocial

-   Puberty

-   Questionnaire

-   School (Demographics)

-   Screen Use

-   Sex

-   Sleep

-   Social

-   Stress

-   SU Attitude

-   SU Environment

-   SU Patterns

-   Task

-   Temperament/Personality

-   Work & School

There are more subdomains in ABCD -- these are just the ones represented in TSP-ABCD.

### source

Source refers to the informant that item was collected from / administered to. Informants can be:

-   Youth

-   Parent

-   Teacher

### table_name

The table_name column refers to ABCD tables, or collections of grouped ABCD variables. Datapoints from the same table were administered and collected together. For more information on the ABCD tables, read through the [ABCD Release Notes](https://wiki.abcdstudy.org/release-notes/start-page.html).

### variable

The items within the name column are unique variables that can either be found directly in the ABCD dataset or were created by the Pelham Lab through manipulating variables from the ABCD dataset.

### label

The label column tells describes the contents of the item in further detail, typically the way in which the question was actually presented to the respondent. Many items, however, have labels that briefly describe the contents of the item, but not the way in which it was presented to the respondent. For items created by the Pelham Lab, labels will provide a description of the contents of the item.

### has_branching_logic

Utilizes the branching_logic column in the ABCD metadata to produce a binary (yes/no) indication of whether the item has branching logic preceding it.

### sensitivity

The sensitivity column captures how jarring the presentation of any given item might be on a survey without context. All items were evaluated by a member of the Pelham Lab as sensitive, maybe sensitive, or not sensitive.

### plab_facet

The plab_facet is a sorting system specifically made to sort the items in the ABCD metadata. The plab_facet was created and reviewed by members of the Pelham Lab \@ UCSD. The [ABCD Release Notes](https://wiki.abcdstudy.org/release-notes/start-page.html) domains were considered in the creation of the plab_facet, but were expanded upon or made more specific in order to classify all items (including items created by the Pelham Lab)

### plab_subfacet

The plab_subfacet is a sorting system within the plab_facet created by members of the Pelham Lab. Categories within the plab_subfacet were only created when clear and necessary categories within a plab_facet category emerged, such that all items in a plab_facet category could fall into a plab_subfacet cateogry of at least three or more items.

### alexsa_facet

The alexsa_facet utilizes the subscales from the Assessment of Liability and EXposure to Substance use and Antisocial behavior for Children (ALEXSA) assessment (Ridenour et al., 2009). The ALEXSA is a child report assessment for predictors of early onset substance abuse and for antisocial behavior.

Items presented in the original ALEXSA assessment fell into one of 34 unique subscales -- all of which are domains in the alexsa_facet. At least two lab members were involved in sorting items and reviewing their placement into specific subscales within the alexsa_facet.

### nobs_00mo, nobs_12mo, nobs_24mo, nobs_36mo, nobs_48mo, nobs_60mo, or nobs_72mo

The nobs (number of observations) columns represent the counts of any given item at any wave. The waves are represented as months from baseline for clarity.

Here is a what each wave in DEAP currently looks like:

00mo: ses-00A

12mo: ses-01A

24mo: ses-02A

36mo: ses-03A

48mo: ses-04A

60mo: ses-05A

72mo: ses-06A
